import { HealthTemplate } from '../types';

export const healthTemplates: HealthTemplate[] = [
  {
    id: 'template_001_hc_completa',
    nombre: 'Historia Clínica Completa',
    descripcion: 'Formato completo de Historia Clínica según normas internacionales HL7',
    categoria: 'historia_clinica_completa',
    tipo: 'predefinida',
    version: '1.0.0',
    estandares_aplicados: ['HL7_v2', 'FHIR_R4'],
    metadatos: {
      departamento: 'Todos',
      nivel_complejidad: 'avanzada',
      requiere_firma_digital: true,
      confidencialidad_nivel: 'altamente_confidencial',
    },
    secciones: [
      {
        id: 'seccion_001',
        nombre: 'Datos de Filiación',
        descripcion: 'Identificación del paciente y datos de contacto',
        orden: 1,
        obligatoria: true,
        campos: [
          {
            nombre_campo: 'nombre_completo',
            etiqueta: 'Nombre Completo',
            tipo_dato: 'texto',
            orden: 1,
            obligatorio: true,
            mapeo_estandares: {
              hl7_field: 'PID-5',
              fhir_path: 'Patient.name.text',
            },
            validaciones: {
              longitud_minima: 5,
              longitud_maxima: 100,
              patron_regex: '^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$',
            },
            configuracion_extraccion: {
              buscar_automaticamente: true,
              metodo_extraccion: ['ocr', 'nlp'],
            },
            security: {
              is_phi: true,
              phi_sensitivity: 'muy_alta',
              hipaa_identifier: true,
            },
          },
          {
            nombre_campo: 'dni_id',
            etiqueta: 'DNI/ID',
            tipo_dato: 'texto',
            orden: 2,
            obligatorio: true,
            security: {
              is_phi: true,
              phi_sensitivity: 'muy_alta',
              hipaa_identifier: true,
            },
          },
          {
            nombre_campo: 'fecha_nacimiento',
            etiqueta: 'Fecha de Nacimiento',
            tipo_dato: 'texto',
            orden: 3,
            obligatorio: true,
            security: {
              is_phi: true,
              phi_sensitivity: 'alta',
              hipaa_identifier: true,
            },
          },
          {
            nombre_campo: 'genero',
            etiqueta: 'Género',
            tipo_dato: 'texto',
            orden: 4,
            obligatorio: false,
          },
          {
            nombre_campo: 'direccion',
            etiqueta: 'Dirección',
            tipo_dato: 'texto',
            orden: 5,
            obligatorio: false,
            security: {
              is_phi: true,
              phi_sensitivity: 'media',
            },
          },
          {
            nombre_campo: 'telefono',
            etiqueta: 'Teléfono',
            tipo_dato: 'texto',
            orden: 6,
            obligatorio: false,
            security: {
              is_phi: true,
              phi_sensitivity: 'media',
            },
          },
          {
            nombre_campo: 'email',
            etiqueta: 'Email',
            tipo_dato: 'texto',
            orden: 7,
            obligatorio: false,
            security: {
              is_phi: true,
              phi_sensitivity: 'media',
            },
          },
        ],
      },
      {
        id: 'seccion_002',
        nombre: 'Motivo de Consulta',
        descripcion: 'Razón principal de la visita médica',
        orden: 2,
        obligatoria: true,
        campos: [
          {
            nombre_campo: 'motivo_consulta',
            etiqueta: 'Motivo de Consulta',
            tipo_dato: 'texto',
            orden: 1,
            obligatorio: true,
          },
        ],
      },
      {
        id: 'seccion_003',
        nombre: 'Antecedentes Personales',
        descripcion: 'Historial médico del paciente',
        orden: 3,
        obligatoria: false,
        campos: [
          {
            nombre_campo: 'alergias',
            etiqueta: 'Alergias',
            tipo_dato: 'texto',
            orden: 1,
            obligatorio: false,
          },
          {
            nombre_campo: 'enfermedades_cronicas',
            etiqueta: 'Enfermedades Crónicas',
            tipo_dato: 'texto',
            orden: 2,
            obligatorio: false,
          },
          {
            nombre_campo: 'cirugias_previas',
            etiqueta: 'Cirugías Previas',
            tipo_dato: 'texto',
            orden: 3,
            obligatorio: false,
          },
          {
            nombre_campo: 'medicacion_actual',
            etiqueta: 'Medicación Actual',
            tipo_dato: 'texto',
            orden: 4,
            obligatorio: false,
          },
        ],
      },
      {
        id: 'seccion_004',
        nombre: 'Exploración Física',
        descripcion: 'Signos vitales y hallazgos físicos',
        orden: 4,
        obligatoria: true,
        campos: [
          {
            nombre_campo: 'tension_arterial',
            etiqueta: 'Tensión Arterial',
            tipo_dato: 'texto',
            orden: 1,
            obligatorio: false,
          },
          {
            nombre_campo: 'frecuencia_cardiaca',
            etiqueta: 'Frecuencia Cardíaca',
            tipo_dato: 'texto',
            orden: 2,
            obligatorio: false,
          },
          {
            nombre_campo: 'temperatura',
            etiqueta: 'Temperatura',
            tipo_dato: 'texto',
            orden: 3,
            obligatorio: false,
          },
          {
            nombre_campo: 'peso',
            etiqueta: 'Peso',
            tipo_dato: 'texto',
            orden: 4,
            obligatorio: false,
          },
          {
            nombre_campo: 'altura',
            etiqueta: 'Altura',
            tipo_dato: 'texto',
            orden: 5,
            obligatorio: false,
          },
          {
            nombre_campo: 'imc',
            etiqueta: 'IMC',
            tipo_dato: 'texto',
            orden: 6,
            obligatorio: false,
          },
          {
            nombre_campo: 'estado_general',
            etiqueta: 'Estado General',
            tipo_dato: 'texto',
            orden: 7,
            obligatorio: false,
          },
        ],
      },
      {
        id: 'seccion_005',
        nombre: 'Diagnóstico y Tratamiento',
        descripcion: 'Diagnóstico y plan terapéutico',
        orden: 5,
        obligatoria: true,
        campos: [
          {
            nombre_campo: 'diagnostico',
            etiqueta: 'Diagnóstico Provisional',
            tipo_dato: 'texto',
            orden: 1,
            obligatorio: true,
          },
          {
            nombre_campo: 'tratamiento',
            etiqueta: 'Tratamiento Prescrito',
            tipo_dato: 'texto',
            orden: 2,
            obligatorio: false,
          },
          {
            nombre_campo: 'observaciones',
            etiqueta: 'Observaciones',
            tipo_dato: 'texto',
            orden: 3,
            obligatorio: false,
          },
        ],
      },
      {
        id: 'seccion_006',
        nombre: 'Información del Médico',
        descripcion: 'Datos del profesional que emite el documento',
        orden: 6,
        obligatoria: true,
        campos: [
          {
            nombre_campo: 'medico',
            etiqueta: 'Nombre del Médico',
            tipo_dato: 'texto',
            orden: 1,
            obligatorio: true,
          },
          {
            nombre_campo: 'numero_colegiado',
            etiqueta: 'Nº Colegiado',
            tipo_dato: 'texto',
            orden: 2,
            obligatorio: false,
          },
          {
            nombre_campo: 'fecha_emision',
            etiqueta: 'Fecha de Emisión',
            tipo_dato: 'texto',
            orden: 3,
            obligatorio: true,
          },
        ],
      },
    ],
  },
];
